/*
 * HEI Admin API
 * _Programmatically connect to a computer programming [school](https://hei.school)._ After [joining us](mailto:contact@hei.school), you can get an identification token from our [dev](https://dev-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=5s8cg50doahmu855rlc8fr6qmp&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-dev.hei.school%2Fwhoami) or [prod](https://prod-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=i8bg538jpfu6mqmqb61m26trd&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-prod.hei.school%2Fwhoami) authentication service. Then, start playing with our system!  The implementation of our API is [publicly disclosed](https://github.com/hei-school/hei-admin-api). You are welcome to try and compromise it. Happy hacking! 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package school.hei.haapi.endpoint.rest.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * StudentTranscriptClaim
 */
@JsonPropertyOrder({
  StudentTranscriptClaim.JSON_PROPERTY_ID,
  StudentTranscriptClaim.JSON_PROPERTY_TRANSCRIPT_ID,
  StudentTranscriptClaim.JSON_PROPERTY_TRANSCRIPT_VERSION_ID,
  StudentTranscriptClaim.JSON_PROPERTY_STATUS,
  StudentTranscriptClaim.JSON_PROPERTY_CREATION_DATETIME,
  StudentTranscriptClaim.JSON_PROPERTY_CLOSED_DATETIME,
  StudentTranscriptClaim.JSON_PROPERTY_REASON
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-05T12:58:43.702904700+03:00[Europe/Moscow]")
public class StudentTranscriptClaim {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_TRANSCRIPT_ID = "transcript_id";
  private String transcriptId;

  public static final String JSON_PROPERTY_TRANSCRIPT_VERSION_ID = "transcript_version_id";
  private String transcriptVersionId;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    OPEN("OPEN"),
    
    CLOSE("CLOSE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_CREATION_DATETIME = "creation_datetime";
  private java.time.Instant creationDatetime;

  public static final String JSON_PROPERTY_CLOSED_DATETIME = "closed_datetime";
  private java.time.Instant closedDatetime;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;


  public StudentTranscriptClaim id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public StudentTranscriptClaim transcriptId(String transcriptId) {
    this.transcriptId = transcriptId;
    return this;
  }

   /**
   * Get transcriptId
   * @return transcriptId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSCRIPT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTranscriptId() {
    return transcriptId;
  }


  @JsonProperty(JSON_PROPERTY_TRANSCRIPT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranscriptId(String transcriptId) {
    this.transcriptId = transcriptId;
  }


  public StudentTranscriptClaim transcriptVersionId(String transcriptVersionId) {
    this.transcriptVersionId = transcriptVersionId;
    return this;
  }

   /**
   * Get transcriptVersionId
   * @return transcriptVersionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSCRIPT_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTranscriptVersionId() {
    return transcriptVersionId;
  }


  @JsonProperty(JSON_PROPERTY_TRANSCRIPT_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranscriptVersionId(String transcriptVersionId) {
    this.transcriptVersionId = transcriptVersionId;
  }


  public StudentTranscriptClaim status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public StudentTranscriptClaim creationDatetime(java.time.Instant creationDatetime) {
    this.creationDatetime = creationDatetime;
    return this;
  }

   /**
   * Get creationDatetime
   * @return creationDatetime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATION_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getCreationDatetime() {
    return creationDatetime;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationDatetime(java.time.Instant creationDatetime) {
    this.creationDatetime = creationDatetime;
  }


  public StudentTranscriptClaim closedDatetime(java.time.Instant closedDatetime) {
    this.closedDatetime = closedDatetime;
    return this;
  }

   /**
   * Get closedDatetime
   * @return closedDatetime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLOSED_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getClosedDatetime() {
    return closedDatetime;
  }


  @JsonProperty(JSON_PROPERTY_CLOSED_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClosedDatetime(java.time.Instant closedDatetime) {
    this.closedDatetime = closedDatetime;
  }


  public StudentTranscriptClaim reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
  }


  /**
   * Return true if this StudentTranscriptClaim object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentTranscriptClaim studentTranscriptClaim = (StudentTranscriptClaim) o;
    return Objects.equals(this.id, studentTranscriptClaim.id) &&
        Objects.equals(this.transcriptId, studentTranscriptClaim.transcriptId) &&
        Objects.equals(this.transcriptVersionId, studentTranscriptClaim.transcriptVersionId) &&
        Objects.equals(this.status, studentTranscriptClaim.status) &&
        Objects.equals(this.creationDatetime, studentTranscriptClaim.creationDatetime) &&
        Objects.equals(this.closedDatetime, studentTranscriptClaim.closedDatetime) &&
        Objects.equals(this.reason, studentTranscriptClaim.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, transcriptId, transcriptVersionId, status, creationDatetime, closedDatetime, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentTranscriptClaim {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    transcriptId: ").append(toIndentedString(transcriptId)).append("\n");
    sb.append("    transcriptVersionId: ").append(toIndentedString(transcriptVersionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creationDatetime: ").append(toIndentedString(creationDatetime)).append("\n");
    sb.append("    closedDatetime: ").append(toIndentedString(closedDatetime)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

